services:
  - type: web
    name: megamoto-campana
    env: node
    buildCommand: |
      apt-get update -y && 
      apt-get install -y chromium-browser && 
      npm install
    startCommand: npm start
    buildpacks:
      - url: heroku/nodejs